version: "3.8"

services:
  mysql-pos:
    image: mysql:8.0
    container_name: pos_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pos_db
    ports:
      - "3306:3306"
    volumes:
      - pos_db_data:/var/lib/mysql

  mysql-ecommerce:
    image: mysql:8.0
    container_name: ecommerce_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3307:3306"
    volumes:
      - ecommerce_db_data:/var/lib/mysql

volumes:
  pos_db_data:
  ecommerce_db_data:
